apiVersion: v1
kind: Namespace
metadata:
  name: linux
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpine
  name: alpine
  namespace: linux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  strategy:
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - image: index.docker.io/alpine
        name: alpine
