---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: test
spec:
  clusterIP: None
  ports:
  - port: 3000
  selector:
    app: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: docker.io/babynin/test-go:0.1
        name: backend
        resources:
          limits:
            memory: 100Mi
          requests:
            memory: 100Mi
        ports:
        - containerPort: 3000
