---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: test
spec:
  clusterIP: None
  ports:
  - port: 3000
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: index.docker.io/babynin/test-go
        name: backend
        resources:
          limits:
            memory: 50Mi
          requests:
            memory: 50Mi
        ports:
        - containerPort: 3000     
