---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: test
spec:
  clusterIP: None
  ports:
  - port: 80
  selector:
    app: frontend     
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: index.docker.io/babynin/test-nginx
        ports:
        - name: nginx
          containerPort: 80          
---
